config/routes.rb
SecretShareAjax::Application.routes.draw do
  resources :users, :only => [:index, :create, :new, :show] do
    resources :secrets, only: [:new]
    resource :friendship, only: [:create, :destroy]
  end
  resource :session, :only => [:create, :destroy, :new]
  resources :secrets, only: [:create]

  root :to => "users#show"
end

app/models/friendship.rb
# == Schema Information
#
# Table name: friendships
#
#  id            :integer          not null, primary key
#  out_friend_id :integer          not null
#  in_friend_id  :integer          not null
#  created_at    :datetime
#  updated_at    :datetime
#

class Friendship < ActiveRecord::Base
  validates :out_friend_id, :in_friend_id, presence: true

  belongs_to :friender,
    class_name: "User",
    foreign_key: :out_friend_id

  belongs_to :friendee,
    class_name: "User",
    foreign_key: :in_friend_id

  def self.can_friend(out_friend_id, in_friend_id)
    return false if out_friend_id == in_friend_id
    return !Friendship.exists?(out_friend_id: out_friend_id,
                               in_friend_id: in_friend_id)
  end

  def self.can_unfriend(out_friend_id, in_friend_id)
    return false if out_friend_id == in_friend_id
    return Friendship.exists?(out_friend_id: out_friend_id,
                               in_friend_id: in_friend_id)
  end
end

app/models/secret.rb
# == Schema Information
#
# Table name: secrets
#
#  id           :integer          not null, primary key
#  title        :string(255)      not null
#  author_id    :integer          not null
#  recipient_id :integer          not null
#  created_at   :datetime
#  updated_at   :datetime
#

class Secret < ActiveRecord::Base
  validates :author_id, :recipient_id, :title, :presence => true

  belongs_to :author, :class_name => "User"
  belongs_to :recipient, :class_name => "User"
  has_many :secret_taggings, inverse_of: :secret
  has_many :tags, through: :secret_taggings
end

app/models/secret_tagging.rb
# == Schema Information
#
# Table name: secret_taggings
#
#  id         :integer          not null, primary key
#  secret_id  :integer
#  tag_id     :integer
#  created_at :datetime
#  updated_at :datetime
#

class SecretTagging < ActiveRecord::Base
  validates :secret, :tag_id, presence: true

  belongs_to :secret
  belongs_to :tag
end

app/models/tag.rb
# == Schema Information
#
# Table name: tags
#
#  id         :integer          not null, primary key
#  name       :string(255)      not null
#  created_at :datetime
#  updated_at :datetime
#

class Tag < ActiveRecord::Base
  validates :name, presence: true

  has_many :secret_taggings, inverse_of: :tag
  has_many :secrets, through: :secret_taggings
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  username        :string(255)      not null
#  password_digest :string(255)      not null
#  created_at      :datetime
#  updated_at      :datetime
#  session_token   :string(255)      not null
#

class User < ActiveRecord::Base
  attr_reader :password

  has_many(
    :authored_secrets,
    :class_name => "Secret",
    :foreign_key => :author_id
  )

  has_many(
    :received_secrets,
    :class_name => "Secret",
    :foreign_key => :recipient_id
  )

  has_many(
    :friendships,
    class_name: "Friendship",
    foreign_key: :out_friend_id
  )

  validates :password_digest, :presence => { :message => "Password can't be blank" }
  validates :password, :length => { :minimum => 6, :allow_nil => true }
  validates :session_token, :presence => true
  validates :username, :presence => true

  after_initialize :ensure_session_token

  def self.find_by_credentials(username, password)
    user = User.find_by_username(username)

    return nil if user.nil?

    user.is_password?(password) ? user : nil
  end

  def self.generate_session_token
    SecureRandom::urlsafe_base64(16)
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def reset_session_token!
    self.session_token = self.class.generate_session_token
    self.save!
    self.session_token
  end

  private
  def ensure_session_token
    self.session_token ||= self.class.generate_session_token
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  helper_method :current_user, :signed_in?

  def current_user
    return nil unless session[:session_token]
    User.find_by_session_token(session[:session_token])
  end

  def signed_in?
    !!current_user
  end

  def sign_in(user)
    @current_user = user
    session[:session_token] = user.reset_session_token!
  end

  def logout_current_user!
    current_user.try(:reset_session_token!)
    session[:session_token] = nil
  end

  def require_current_user!
    redirect_to new_session_url unless signed_in?
  end

  def require_no_current_user!
    redirect_to user_url(current_user) if signed_in?
  end
end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController
  def create
    @out_friend_id = current_user.id
    @in_friend_id = params[:user_id]
    @friendship = Friendship.new(out_friend_id: @out_friend_id,
                                 in_friend_id: @in_friend_id)

    if @friendship.save
      render :json => @friendship
    else
      flash[:errors] = @friendship.errors.full_messages
      redirect_to users_url
    end

  end

  def destroy
    @user = Friendship.find(params[:user_id])
    @friendship = Friendship.find_by(out_friend_id: current_user,
                                     in_friend_id: @user)
    @friendship.destroy
    head :ok
  end
end

app/controllers/secrets_controller.rb
class SecretsController < ApplicationController
  def new
    @user = User.find(params[:user_id])
  end

  def create
    @user = User.find(params[:secret][:recipient_id])
    @secret = Secret.new(secret_params)
    @secret.author_id = current_user.id
    # @secret.tag_ids

    if @secret.save
      render :json => @secret
    else
      flash.now[:errors] = @secret.errors.full_messages
      render :new
    end
  end

  private
  def secret_params
    params.require(:secret).permit(:title, :recipient_id, tag_ids: [])
  end

  def tag_params
    # params.permit(tags:
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_filter :require_no_current_user!, :only => [:create, :new]
  before_filter :require_current_user!, :only => [:destroy]

  def create
    user = User.find_by_credentials(
      params[:user][:username],
      params[:user][:password]
    )

    if user.nil?
      render :json => "Credentials were wrong"
    else
      self.sign_in(user)
      redirect_to user_url(user)
    end
  end

  def destroy
    logout_current_user!
    redirect_to new_session_url
  end

  def new
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :require_current_user!, :only => [:index, :show]
  before_filter :require_no_current_user!, :only => [:create, :new]

  def index
    @users = User.all
    @friendships = current_user.friendships
  end

  def create
    @user = User.new(user_params)

    if @user.save
      sign_in(@user)
      redirect_to user_url(@user)
    else
      render :json => @user.errors.full_messages
    end
  end

  def new
    @user = User.new
  end

  def show
    if !params.include?(:id)
      redirect_to user_url(current_user)
      return
    end

    @user = User.find(params[:id])
  end

  private

  def user_params
    params.require(:user).permit(:username, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/friendships_helper.rb
module FriendshipsHelper
end

app/helpers/secrets_helper.rb
module SecretsHelper
end

app/views/friendships/_form.html.erb
<%= button_to "Friend Me!", user_friendships_url(user) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SecretShareAjax</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<% if signed_in? %>
  <ul>
    <li>Logged in as: <%= current_user.username %></li>
    <li><%= button_to "Logout", session_url, :method => :delete %></li>
  </ul>
<% end %>

<%= yield %>

</body>
</html>

app/views/secrets/_form.html.erb
<form action="<%= secrets_url %>" method="post" accept-charset="utf-8" id="secret-form">

  <input type="hidden" name="authenticity_token"
         value="<%= form_authenticity_token %>">

  <label>
    Title:
    <input type="text" name="secret[title]">
  </label>

  <input type="hidden" name="secret[recipient_id]" value="<%= @user.id %>">

  <a id="show-tags">Add Tag</a>
  <div id="tag-container"></div>

  <p><input type="submit" value="Continue &rarr;"></p>
</form>

<script type="application/json" id="bootstrapped_tags">
  { "tags": <%= Tag.all.to_json.html_safe %> }
</script>

<script type="text/template" id="tag-selector">
  <select name="secret[tag_ids][]">
    <%% _.each(tags, function(tag, idx) { %>
      <option value="<%%= tag.id %>"><%%= tag.name %></option>
    <%% }); %>
  </select>
</script>

<script>
  var addSecretTagSelect = function() {
    var template = _.template($('#tag-selector').html());

    var content = template({
      tags: JSON.parse($('#bootstrapped_tags').html()).tags
    });
    $('#tag-container').append(content);
  }

  $(function() {
    $('#show-tags').on('click', function() {
      addSecretTagSelect();
    });
  });

</script>

app/views/secrets/new.html.erb
<form action="<%= secrets_url %>" method="post" accept-charset="utf-8">

  <input type="hidden" name="authenticity_token"
         value="<%= form_authenticity_token %>">

  <label>
    Title:
    <input type="text" name="secret[title]">
  </label>

  <input type="hidden" name="secret[recipient_id]" value="<%= @user.id %>">

  <p><input type="submit" value="Continue &rarr;"></p>
</form>

app/views/users/_form.html.erb
<% action = (user.persisted? ? user_url(user) : users_url) %>
<% method = (user.persisted? ? "put" : "post") %>
<% message = (user.persisted? ? "Update user" : "Create user") %>

<form action="<%= action %>" method="post">
  <input
     name="_method"
     type="hidden"
     value="<%= method %>">
  <input
     name="authenticity_token"
     type="hidden"
     value="<%= form_authenticity_token %>">

  <label for="user_username">Username</label>
  <input
     id="user_username"
     name="user[username]"
     type="text">
  <br>

  <label for="user_password">Password</label>
  <input
     id="user_password"
     name="user[password]"
     type="password">
  <br>

  <input type="submit" value="<%= message %>">
</form>

app/views/users/index.html.erb
<h1>All Users</h1>

<ul>
<% @users.each do |user| %>
  <li>
    <%= user.username %>

    <% if Friendship.can_friend(current_user, user) %>
      <% friendship_status = "can-friend" %>
    <% elsif Friendship.can_unfriend(current_user, user) %>
      <% friendship_status = "can-defriend" %>
    <% else %>
      <% friendship_status = "self" %>
    <% end %>

    <div data-user="<%= user.id %>" class="friend-buttons <%= friendship_status %>">
      <button class="friend">Friend Me!</button>
      <button class="defriend">
        Destroy Friendship!</button>
    </div>
  </li>
<% end %>
</ul>

<script>

  var toggleFriendButtons = function(event) {
    $(event.currentTarget.parentElement).toggleClass('can-friend can-defriend');
  }

  $('ul').on('click', '.friend', function(event) {

    var $friend_id = (event.currentTarget.parentElement.dataset.user);
    $.ajax({
      url: "/users/" + $friend_id + "/friendship",
      type: 'POST',
      success: function() {
        toggleFriendButtons(event);
      }
    });
  });

  $('ul').on('click', '.defriend', function(event) {
    console.log(event);

    var $friend_id = (event.currentTarget.parentElement.dataset.user);
    $.ajax({
      url: "/users/" + $friend_id + "/friendship",
      type: 'DELETE',
      success: function() {
        toggleFriendButtons(event);
      }
    });
  })
</script>

app/views/users/new.html.erb
<h1>Create User</h1>

<%= render "form", :user => @user %>

app/views/users/show.html.erb
<h1><%= @user.username %></h1>

<h2>Secrets</h2>
<ul id="secrets">
  <% @user.received_secrets.each do |secret| %>
    <li><%= secret.title %></li>
  <% end %>
</ul>

<%= render 'secrets/form' %>

<script>

$(function() {
  var addSecret = function(secret) {
    $('#secrets').append('<li>' + secret.title + '</li>');
  }

  $('#secret-form').on('submit', function(event) {
    event.preventDefault();

    var $form = $(this);
    var formData = $(this).serializeJSON();

    $.ajax({
      url: $form.attr('action'),
      type: 'POST',
      data: formData,
      success: function(model) {
        addSecret(model);
        $('#secret-form').find("input[type=text]").val("");
      }
    });
  })
});

</script>